INSERT INTO produtos (nome, descricao, preco, ativo, categoria) VALUES
('Notebook Dell Inspiron', 'Notebook para uso diário', 3500.00, true, 'ELETRONICOS'),
('Notebook Lenovo ThinkPad', 'Notebook corporativo', 5200.00, true, 'ELETRONICOS'),
('Smartphone Samsung Galaxy S21', 'Celular Android', 2800.00, true, 'ELETRONICOS'),
('Smartphone iPhone 13', 'Celular iOS', 5200.00, true, 'ELETRONICOS'),
('Monitor LG 24"', 'Monitor Full HD', 950.00, true, 'ELETRONICOS'),
('Teclado Mecânico', 'Teclado gamer RGB', 420.00, true, 'ELETRONICOS'),
('Mouse Gamer', 'Mouse com DPI ajustável', 210.00, true, 'ELETRONICOS'),
('Headset Bluetooth', 'Headset sem fio', 350.00, true, 'ELETRONICOS'),
('Impressora HP', 'Impressora multifuncional', 780.00, true, 'ELETRONICOS'),
('Webcam Logitech', 'Webcam Full HD', 390.00, true, 'ELETRONICOS'),

-- ROUPAS (30)
('Camiseta Básica', 'Camiseta de algodão', 49.90, true, 'ROUPAS'),
('Camisa Social', 'Camisa social masculina', 129.90, true, 'ROUPAS'),
('Calça Jeans', 'Calça jeans azul', 159.90, true, 'ROUPAS'),
('Jaqueta Jeans', 'Jaqueta casual', 229.90, true, 'ROUPAS'),
('Moletom', 'Moletom com capuz', 179.90, true, 'ROUPAS'),
('Vestido Casual', 'Vestido feminino', 199.90, true, 'ROUPAS'),
('Saia Midi', 'Saia estilo midi', 139.90, true, 'ROUPAS'),
('Blusa Feminina', 'Blusa leve', 89.90, true, 'ROUPAS'), 
('Shorts Jeans', 'Shorts para verão', 99.90, true, 'ROUPAS'),
('Casaco de Inverno', 'Casaco térmico', 349.90, true, 'ROUPAS'),

-- ALIMENTOS (40)
('Arroz Branco 5kg', 'Arroz tipo 1', 32.90, true, 'ALIMENTOS'),
('Feijão Carioca 1kg', 'Feijão selecionado', 8.90, true, 'ALIMENTOS'),
('Macarrão Espaguete', 'Macarrão italiano', 5.90, true, 'ALIMENTOS'),
('Azeite de Oliva', 'Azeite extra virgem', 29.90, true, 'ALIMENTOS'),
('Café Torrado', 'Café tradicional', 17.90, true, 'ALIMENTOS'),
('Leite Integral', 'Leite longa vida', 4.90, true, 'ALIMENTOS'),
('Chocolate Amargo', 'Chocolate 70% cacau', 9.90, true, 'ALIMENTOS'),
('Biscoito Integral', 'Biscoito saudável', 6.50, true, 'ALIMENTOS'),
('Suco de Laranja', 'Suco natural', 7.90, true, 'ALIMENTOS'),
('Granola', 'Granola com frutas', 14.90, true, 'ALIMENTOS'),

-- SERVICOS (40)
('Assinatura Streaming', 'Plano mensal de streaming', 39.90, true, 'SERVICOS'),
('Curso Online Java', 'Curso completo de Java', 499.90, true, 'SERVICOS'),
('Curso React', 'Curso React para iniciantes', 399.90, true, 'SERVICOS'),
('Manutenção de Computador', 'Serviço técnico', 150.00, true, 'SERVICOS'),
('Consultoria TI', 'Consultoria especializada', 250.00, true, 'SERVICOS'),
('Design Gráfico', 'Criação de identidade visual', 600.00, true, 'SERVICOS'),
('Hospedagem de Site', 'Plano anual', 199.90, true, 'SERVICOS'),
('Domínio Internet', 'Registro anual', 49.90, true, 'SERVICOS'),
('Suporte Técnico', 'Suporte remoto', 120.00, true, 'SERVICOS'),
('Plano de Backup', 'Backup em nuvem', 89.90, true, 'SERVICOS');
